app:
    resource: '@AppBundle/Controller/'
    type: annotation
    defaults: {_format:json}

data_integration.swagger_ui:
    path: /api/doc/
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
