services:
  base_service:
    abstract: true
    class: AppBundle\Service\BaseService
    calls:
      - [ setServiceContainer, ["@service_container"] ]
      - [ setEntityManager, ["@doctrine.orm.entity_manager"] ]
      - [ setLogger, ["@monolog.logger.exception"] ]
      - [ setTranslator, ["@translator.default"] ]

  request_listener:
    class: AppBundle\EventListener\RequestListener
    parent: base_service
    arguments: ["@monolog.logger.api"]
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
      - { name: monolog.logger, channel: api }
    public: true

  response_listener:
    class: AppBundle\EventListener\ResponseListener
    parent: base_service
    arguments: ["@monolog.logger.api"]
    tags:
      - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

  eat24.exception_listener:
    class: AppBundle\EventListener\ExceptionListener
    parent: base_service
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
      - { name: monolog.logger, channel: exception }
    public: true

  authentication_token:
    class: AppBundle\Service\AuthenticateToken
    parent: base_service
    public: true

  api_response:
    class: AppBundle\Service\ApiResponse
    parent: base_service
    public: true

  app.utils:
    class: AppBundle\Service\Utils
    parent: base_service
    public: true

  app.user_api_service:
    class: AppBundle\Service\UserApiProcessingService
    parent: base_service
    public: true

  app.salesforce_api_service:
    class: AppBundle\Service\SalesforceApiProcessingService
    parent: base_service
    public: true

  app.quickbooks_api_service:
    class: AppBundle\Service\QuickbooksApiProcessingService
    parent: base_service
    public: true

  salesforce_service:
    class: AppBundle\Service\SalesforceService
    parent: base_service
    public: true

  quickbooks_service:
    class: AppBundle\Service\QuickbooksService
    parent: base_service
    public: true
